name: scientific
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python
  - pytorch
  - jupyterlab
  - tqdm
  - ipywidgets
  - pip
  - pip:
    - stable-baselines3[extra]
    - seaborn
    - puffbird